@Candidatos.Api_HostAddress = http://localhost:5290

POST {{Candidatos.Api_HostAddress}}/api/candidatos
Content-Type: application/json

{
  "nomeCompleto": "Maria da Silva",
  "email": "maria.silva@exemplo.com",
  "telefone": "(41) 99999-8888",
  "areaInteresse": "Desenvolvimento",
  "resumoProfissional": "Estudante de Análise e Desenvolvimento de Sistemas."
}

###

POST {{Candidatos.Api_HostAddress}}/api/candidatos
Content-Type: application/json

{
  "nomeCompleto": "",
  "email": "email-invalido"
}

###

GET {{Candidatos.Api_HostAddress}}/api/candidatos

###

GET {{Candidatos.Api_HostAddress}}/api/candidatos/1

###

GET {{Candidatos.Api_HostAddress}}/api/candidatos/999999

###

POST {{Candidatos.Api_HostAddress}}/api/curriculos/extrair
Content-Type: multipart/form-data; boundary=limite

--limite
Content-Disposition: form-data; name="arquivo"; filename="curriculo-ficticio.pdf"
Content-Type: application/pdf

< ../../../exemplos/curriculo-ficticio.pdf
--limite--

###

POST {{Candidatos.Api_HostAddress}}/api/curriculos/extrair
Content-Type: multipart/form-data; boundary=limite

--limite
Content-Disposition: form-data; name="arquivo"; filename="curriculo-protegido.pdf"
Content-Type: application/pdf

< ../../../exemplos/curriculo-protegido.pdf
--limite--
